# Generated by Django 4.0.2 on 2022-02-07 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todolistitems',
            name='content',
            field=models.TextField(),
        ),
    ]
